SELECT
    ID,
    EMAIL,
    TYPE,
    FIRST_NAME,
    LAST_NAME,
    USER_ID,
    USER_ID_INCLUDING_INACTIVE,
    CREATED_AT,
    UPDATED_AT,
    ARCHIVED
FROM {{ env_var('SNOWFLAKE_DATABASE') }}.{{ env_var('SNOWFLAKE_SCHEMA') }}.OWNERS
