SELECT COUNTRY_ISO2,
       STATE_ISO2,
       ID,
       CITY_NAME,
       LATITUDE,
       LONGITUDE,
       CURRENT_TIMESTAMP AS LAST_UPDATED_DATETIME
FROM {{ env_var('SNOWFLAKE_DATABASE') }}.{{ env_var('SNOWFLAKE_SCHEMA') }}.CITIES